// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smpvvyisldlcbyobezkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtcHZ2eWlzbGRsY2J5b2Jlemt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTUxNTcsImV4cCI6MjA3MTY5MTE1N30.npOw3xjMWuOerLWQ8Fv916Y4ebscShioNNKFYzhI7wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});